In [28]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix, classification_report,roc_curve,roc_auc_score,f1_score
from sklearn.naive_bayes import GaussianNB

In [5]:
df=pd.read_csv('car_evaluation.csv')

In [6]:
df.shape

(1727, 7)

In [7]:
df.head()

vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc

In [8]:
df.columns=['Buying','Maint','Doors','Persons','LugBoot','Safety','Evaluation']
df.head()

Buying  Maint Doors Persons LugBoot Safety Evaluation
0  vhigh  vhigh     2       2   small    med      unacc
1  vhigh  vhigh     2       2   small   high      unacc
2  vhigh  vhigh     2       2     med    low      unacc
3  vhigh  vhigh     2       2     med    med      unacc
4  vhigh  vhigh     2       2     med   high      unacc

In [9]:
df.sample(10)

Buying  Maint  Doors Persons LugBoot Safety Evaluation
483    high  vhigh      3    more     big    med      unacc
557    high   high      2    more   small    low      unacc
1433    low   high      3       2     med    low      unacc
691    high    med      3       4     big   high        acc
651    high    med      2       2     med    med      unacc
1164    med    med  5more       2     med    med      unacc
1571    low    med      4       2     big    low      unacc
907     med  vhigh      3       4     big   high        acc
1143    med    med      4       4   small    med        acc
699    high    med      3    more     big    med        acc

In [10]:
df.isnull().sum()

Buying        0
Maint         0
Doors         0
Persons       0
LugBoot       0
Safety        0
Evaluation    0
dtype: int64

In [11]:
df.describe()

Buying Maint Doors Persons LugBoot Safety Evaluation
count    1727  1727  1727    1727    1727   1727       1727
unique      4     4     4       3       3      3          4
top      high  high     4       4     big   high      unacc
freq      432   432   432     576     576    576       1209

In [13]:
df.columns

Index(['Buying', 'Maint', 'Doors', 'Persons', 'LugBoot', 'Safety',
       'Evaluation'],
      dtype='object')

In [15]:
df['Evaluation'].value_counts().sort_index()

acc       384
good       69
unacc    1209
vgood      65
Name: Evaluation, dtype: int64

In [19]:
df.Doors.replace(('5more'),('5'),inplace=True)
df.Persons.replace(('more'),('5'),inplace=True)

In [20]:
df.head()

Buying  Maint Doors Persons LugBoot Safety Evaluation
0  vhigh  vhigh     2       2   small    med      unacc
1  vhigh  vhigh     2       2   small   high      unacc
2  vhigh  vhigh     2       2     med    low      unacc
3  vhigh  vhigh     2       2     med    med      unacc
4  vhigh  vhigh     2       2     med   high      unacc

In [21]:
X=df.drop(['Evaluation'],axis=1)
y=df['Evaluation']

In [23]:
X.head()

Buying  Maint Doors Persons LugBoot Safety
0  vhigh  vhigh     2       2   small    med
1  vhigh  vhigh     2       2   small   high
2  vhigh  vhigh     2       2     med    low
3  vhigh  vhigh     2       2     med    med
4  vhigh  vhigh     2       2     med   high

In [24]:
y.head()

0    unacc
1    unacc
2    unacc
3    unacc
4    unacc
Name: Evaluation, dtype: object

In [25]:
X=pd.get_dummies(X,prefix_sep='_',drop_first=True)

In [26]:
X.sample(10)

Buying_low  Buying_med  Buying_vhigh  Maint_low  Maint_med  Maint_vhigh  \
868            0           1             0          0          0            1   
886            0           1             0          0          0            1   
1405           1           0             0          0          0            0   
444            0           0             0          0          0            1   
1048           0           1             0          0          0            0   
951            0           1             0          0          0            1   
1012           0           1             0          0          0            0   
13             0           0             1          0          0            1   
1127           0           1             0          0          1            0   
431            0           0             0          0          0            1   

      Doors_3  Doors_4  Doors_5  Persons_4  Persons_5  LugBoot_med  \
868         0        0        0          0          0            1   
886         0        0        0          0          1            1   
1405        0        0        0          0          0            0   
444         0        0        0          1          0            1   
1048        0        1        0          0          1            1   
951         0        0        1          0          0            0   
1012        1        0        0          1          0            1   
13          0        0        0          1          0            1   
1127        1        0        0          0          1            1   
431         0        0        0          0          0            0   

      LugBoot_small  Safety_low  Safety_med  
868               0           0           0  
886               0           0           0  
1405              1           0           0  
444               0           0           1  
1048              0           0           0  
951               0           0           1  
1012              0           0           0  
13                0           0           0  
1127              0           1           0  
431               1           1           0

In [27]:
y.describe()

count      1727
unique        4
top       unacc
freq       1209
Name: Evaluation, dtype: object

In [29]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=21)

In [30]:
clf_gnb=GaussianNB()
clf_gnb.fit(X_train,y_train)

GaussianNB()

In [32]:
y_pred=clf_gnb.predict(X_test)

In [33]:
print('Training Accuracy:',clf_gnb.score(X_train,y_train))
print('Testing Accuracy:',clf_gnb.score(X_test,y_test))

Training Accuracy: 0.49503311258278143
Testing Accuracy: 0.47398843930635837


In [34]:
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[ 37  52   0  25]
 [  0  10   0   5]
 [107  66 183  18]
 [  0   0   0  16]]


In [35]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         acc       0.26      0.32      0.29       114
        good       0.08      0.67      0.14        15
       unacc       1.00      0.49      0.66       374
       vgood       0.25      1.00      0.40        16

    accuracy                           0.47       519
   macro avg       0.40      0.62      0.37       519
weighted avg       0.79      0.47      0.55       519

